# Example: Deploy to Pantheon with Slack Notifications
# This is a comprehensive example showing how to configure Slack notifications
# Copy and modify this file for your specific deployment needs

name: Deploy to Pantheon with Slack Notifications

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
      - main
    types: [ closed ]
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged == true }}
    uses: Square360/shared-pantheon-workflows/.github/workflows/reusable-deploy-pantheon.yml@main
    with:
      pantheon_site: ${{ vars.PANTHEON_SITE }}
      target_env: "dev"
      backup_hours_threshold: 6
      run_semantic_release: true
      # Slack notification configuration
      slack_channel: ${{ vars.SLACK_CHANNEL }}           # e.g., "#deployments"
    secrets:
      PANTHEON_SSH_KEY: ${{ secrets.PANTHEON_SSH_KEY }}
      PANTHEON_MACHINE_TOKEN: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
      CI_GH_TOKEN: ${{ secrets.CI_GH_TOKEN }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}     # Slack bot token